version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: eventbrites/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6850
      DatabaseServer: mssqlserver
      DatabaseName: catalogDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6850:80"
    container_name: eventbritescatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://192.168.86.121:6701
      CallBackUrl: http://localhost:6852
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6852:80"
    container_name: eventshop
    networks:
      - frontend
    depends_on:
      - catalog

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      Mvcclient: http://localhost:6852
    ports:
      - "6701:80"
    container_name: eventstokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver


  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: jewels/cartapi
    environment:
      IdentityUrl: http://192.168.86.121:6701
      ConnectionString: basket.data
    ports:
      - "6815:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1448:1433"
    container_name: eventbritessqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name:basketdata
    ports:
      - "6081:6379"
    networks:
      - backend
