version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: eventbrites/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6850
      DatabaseServer: mssqlserver
      DatabaseName: catalogDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6850:80"
    container_name: eventbritescatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: jewels/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
    ports:
      - "6852:80"
    container_name: eventshop
    networks:
      - frontend
    depends_on:
      - catalog


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1448:1433"
    container_name: eventbritessqlserver
    networks:
      - backend