version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: eventbrites/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6810
      DatabaseServer: mssqlserver
      DatabaseName: catalogDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6810:80"
    container_name: eventbritescatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1448:1433"
    container_name: eventbritessqlserver
    networks:
      - backend